---
- name: Local Setup
  hosts: 127.0.0.1
  roles:
    - { role: systemli.onion }
  connection: local
  become: yes

  tasks:
    - name: update the apt package index i.e. apt-get update
      apt: update_cache=yes
  
    - name: upgrade system packages i.e. apt-get upgrade
      apt: upgrade=yes

    - name: install vim, git
      apt:
        name: vim,git
        update_cache: yes
        
    - name: Ensures SSD is mounted
      mount:
        path: /mnt
        src: /dev/sda1
        fstype: ext4
        opts: rw,noauto
        state: present
        
    - name: Creates results directory
      file:
        owner: ergadmin
        group: ergadmin
        path: /mnt/results
        state: directory

    - name: Creates scripts directory
      file:
        owner: ergadmin
        group: ergadmin
        path: /home/ergadmin/scripts
        state: directory

    - name: Generate keys
      user:
        name: ergadmin
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: "/home/ergadmin/.ssh/id_rsa"
  
    - name: copy key to authorized_keys
      shell: "ssh ergadmin@targets.erg.abdn.ac.uk 'mkdir -p .ssh && cat >> .ssh/authorized_keys' < ~/.ssh/id_rsa.pub"
      become: yes
      become_user: ergadmin
      
    - name: cp script
      copy:
        src: scripts/register.sh 
        dest: /home/ergadmin/scripts/register.sh
        owner: ergadmin
        group: ergadmin
        mode: 0777

    - name: run registration script
      shell: "/home/ergadmin/scripts/register.sh > /home/ergadmin/$HOSTNAME"
      args:
        executable: /bin/bash

    - name: copies results of latest resigter script to erg
      shell: "scp /home/ergadmin/$HOSTNAME ergadmin@erg-controller.erg.abdn.ac.uk:registered/"
      become: yes
      become_user: ergadmin
    
    - name: Set up tom as an admin
      authorized_key:
        user: ergadmin
        state: present
        key: "{{ lookup('file', 'public_keys/tom-pub.rsa') }}"
    
    - name: Set up ana as an admin
      authorized_key:
        user: ergadmin
        state: present
        key: "{{ lookup('file', 'public_keys/ana-pub.rsa') }}"

    - name: set the vimrc
      copy:
        src: vimrc 
        dest: /home/ergadmin/.vimrc
        owner: ergadmin
        group: ergadmin
        mode: 0700

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                   regexp="^PasswordAuthentication"
                   line="PasswordAuthentication no"
                   state=present
      notify: restart sshd

    - name: Creates results directory
      file:
        path: /mnt/results
        owner: ergadmin
        group: ergadmin
        state: directory
      become: yes
      become_user: ergadmin

    - name: rsync results directory to erg
      command: rsync -avz /mnt/results/ ergadmin@erg-controller.erg.abdn.ac.uk:results
      become: yes
      become_user: ergadmin

    - name: rsyncs latest playbook file in ergadmin home
      command: rsync -avz ergadmin@erg-controller.erg.abdn.ac.uk:playbook.yaml /home/ergadmin/playbook.yaml
      become: yes
      become_user: ergadmin

    - name: makes playbook run every 30 minutes
      cron:
        name: Run ansible every 30 min
        minute: 30
        job: ansible-playbook /home/ergadmin/playbook.yaml

    - name: makes playbook run at reboot
      cron:
        name: Run ansible at reboot
        special_time: reboot
        job: ansible-playbook /home/ergadmin/playbook.yaml

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted 

